name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Set up MSYS2 with necessary tools
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-qt5-static

      # Download and extract OpenSSL binaries
      - name: Download and extract OpenSSL
        run: |
          curl -L -o OpenSSL_mingw_build.rar https://www.eliboa.com/OpenSSL_mingw_build.rar
          mkdir -p OpenSSL/OpenSSL_mingw64
          7z x OpenSSL_mingw_build.rar -oOpenSSL/tmp
          mv OpenSSL/tmp/OpenSSL_mingw32/* OpenSSL/OpenSSL_mingw64/

      # Build the project
      - name: Build
        shell: msys2 {0}
        run: |
          ln -s $(pwd) ~/NxNandManager
          cd ~/NxNandManager/NxNandManager/gui

          # Generate the Makefile
          /mingw64/qt5-static/bin/qmake.exe NxNandManager.pro 'CONFIG += STATIC ARCH64'

          # Patch Makefile.Release to update OpenSSL paths
          sed -i "s|../../../OpenSSL_mingw64/lib|$(pwd)/OpenSSL/OpenSSL_mingw64/lib|g" Makefile.Release
          sed -i "s|../../../OpenSSL_mingw64/include|$(pwd)/OpenSSL/OpenSSL_mingw64/include|g" Makefile.Release

          # Build the project
          make -f Makefile.Release -j"$(nproc)"

          # Copy the artifacts to the GitHub workspace
          mkdir -p $GITHUB_WORKSPACE/bin
          cp release/NxNandManager.exe $GITHUB_WORKSPACE/bin
          cp ../virtual_fs/dokan/x64/dokan1.dll $GITHUB_WORKSPACE/bin

      # Upload the built artifact
      - uses: actions/upload-artifact@v3
        with:
          name: NxNandManager
          path: bin/*
